#+TITLE: Performance comparison of regular expression engines

the original test environment by *dark100* at
[[http://sljit.sourceforge.net/regex_perf.html][http://sljit.sourceforge.net/regex_perf.html]]

best view [here](https://nasciiboy.github.io/raptorVSworld/)

* Introduction

  Processing text or raw byte-sequence are among the common tasks performed by
  most software tools.  These tasks usually involve pattern matching
  algorithms, and the most popular tool for such purpose is regular
  expressions. Regular expressions has been evolved a lot since Kleene defined
  the regular sets in the 1950's. Today we have several widely used regular
  expression engines which have different [[http://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines][features]] which makes any performance
  comparison a difficult task, since a *faster* engine is not necessary
  *better*. Depending on the use case it might be enough to know whether a
  POSIX compatible regular expression matches to a line, even the position of
  the match is unneeded (/grep utility/). On the contrary other use cases
  require the position of capturing brackets, unicode support, conditional and
  atomic block (handling a byte sequence as a single character, like 'sch' in
  German language) support just to name a few. The former case needs a less
  sophisticated algorithm, which is likely be much faster than the latter, but
  again, that does not mean the former is *better*. More about these engine
  types can be found [[http://sljit.sourceforge.net/regex_compare.html][here]].

* Participants

  The following popular engines were choosen:

  - [[http://www.pcre.org/][PCRE2 10.22]]
  - [[https://github.com/laurikari/tre/][tre 0.8.0]]
  - [[http://www.geocities.jp/kosako3/oniguruma/][Oniguruma 6.1.3]]
  - [[https://github.com/google/re2][re2 by Google]]
  - re2 (by Gogle) (Golang)
  - [[http://sljit.sourceforge.net/pcre.html][PCRE2 10.22 with sljit JIT compiler support]]


  and

  - [[https://github.com/nasciiboy/RecursiveRegexpRaptor][regexp3]]
  - [[https://github.com/nasciiboy/RecursiveRegexpRaptor-4][regexp4]]
  - [[https://github.com/nasciiboy/regexp4][regexp4 (Golang)]]


  Before anyone jump to any conclusions, I should note the followings:

  - The engines were not fine tuned (because of my lack of knowledge about
    their internal workings).  I just compiled them with the default options. I
    know enabling or disabling some features can heavily affect the results. If
    you feel that you have a better configuration just drop me an e-mail and I
    will update the results ([[mailto:nasciiboy@gmail.com]]).

  - The regular expression engines are compiled with =-O3= to allow the best performance.

  - This comparison page was inspired by the work of John Maddock (See his own
    regex comparison [[http://www.boost.org/doc/libs/1_41_0/libs/regex/doc/gcc-performance.html][here]]).  The input is also the same he used before:
    [[http://www.gutenberg.org/files/3200/old/mtent12.zip][mtent12.zip]].  It is a text file (e-book) which size is about 20 Mbytes.

  - Only common patterns are selected, they are not pathological cases nor have
    any PERL specific features. The comparison was caseful.

* Results
** x86-64 bit Intel Cerelon 847 1.1GHz (GCC 7.2.0, Go 1.9.1 – GNU/Linux)

   #+BEGIN_HTML
     <table class="results" border="1" width="100%">
     <thead>
     <tr><th>Regular expression</th><th class="std" class="std" >tre</th><th class="std" class="std" >re2Golang</th><th class="std" class="std" >re2</th><th class="std" class="std" >pcre-JIT</th><th class="std" class="std" >pcre-DFA</th><th class="std" class="std" >pcre</th><th class="std" class="std" >onig</th><th class="raptor" class="raptor" >regexp4Golang</th><th class="raptor" class="raptor" >regexp4</th><th class="raptor" class="raptor" >regexp3</th></tr>
     </thead>
     <tbody>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;.|\n&#34;</tr></td><tr class="raptor" ><td>&#34;.&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >6486ms (19285324)</td><td class="re2Golang" class="std" class="tbody" >34159ms (19285324)</td><td class="re2" class="std" class="tbody" >9072ms (19285324)</td><td class="pcre-JIT" class="std" class="tbody" >1130ms (19285324)</td><td class="pcre-DFA" class="std" class="tbody" >6677ms (19285324)</td><td class="pcre" class="std" class="tbody" >4448ms (19285324)</td><td class="onig" class="std" class="tbody" >12876ms (19285324)</td><td class="regexp4Golang" class="raptor" class="tbody" >1553ms (19285324)</td><td class="regexp4" class="raptor" class="tbody" >605ms (19285324)</td><td class="regexp3" class="raptor" class="tbody" >1808ms (19285324)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;\d&#34;</tr></td><tr class="raptor" ><td>&#34;:d&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1044ms (27084)</td><td class="re2Golang" class="std" class="tbody" >3166ms (27084)</td><td class="re2" class="std" class="tbody" >134ms (27084)</td><td class="pcre-JIT" class="std" class="tbody" >55ms (27084)</td><td class="pcre-DFA" class="std" class="tbody" >68ms (27084)</td><td class="pcre" class="std" class="tbody" >65ms (27084)</td><td class="onig" class="std" class="tbody" >127ms (27084)</td><td class="regexp4Golang" class="raptor" class="tbody" >1340ms (27084)</td><td class="regexp4" class="raptor" class="tbody" >594ms (27084)</td><td class="regexp3" class="raptor" class="tbody" >1853ms (27084)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;\S&#34;</tr></td><tr class="raptor" ><td>&#34;:S&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >4633ms (15451664)</td><td class="re2Golang" class="std" class="tbody" >32530ms (15451664)</td><td class="re2" class="std" class="tbody" >7405ms (15451664)</td><td class="pcre-JIT" class="std" class="tbody" >931ms (15451664)</td><td class="pcre-DFA" class="std" class="tbody" >4593ms (15451664)</td><td class="pcre" class="std" class="tbody" >3086ms (15451664)</td><td class="onig" class="std" class="tbody" >10453ms (15451664)</td><td class="regexp4Golang" class="raptor" class="tbody" >2056ms (15451664)</td><td class="regexp4" class="raptor" class="tbody" >810ms (15451664)</td><td class="regexp3" class="raptor" class="tbody" >1912ms (15451664)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;\S+&#34;</tr></td><tr class="raptor" ><td>&#34;:S+&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >2565ms (3414592)</td><td class="re2Golang" class="std" class="tbody" >8000ms (3414592)</td><td class="re2" class="std" class="tbody" >1957ms (3414592)</td><td class="pcre-JIT" class="std" class="tbody" >333ms (3414592)</td><td class="pcre-DFA" class="std" class="tbody" >1619ms (3414592)</td><td class="pcre" class="std" class="tbody" >924ms (3414592)</td><td class="onig" class="std" class="tbody" >3114ms (3414592)</td><td class="regexp4Golang" class="raptor" class="tbody" >1521ms (3414592)</td><td class="regexp4" class="raptor" class="tbody" >654ms (3414592)</td><td class="regexp3" class="raptor" class="tbody" >1059ms (3414592)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;\w&#34;</tr></td><tr class="raptor" ><td>&#34;:w&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >4769ms (14751878)</td><td class="re2Golang" class="std" class="tbody" >32506ms (14751878)</td><td class="re2" class="std" class="tbody" >7052ms (14751878)</td><td class="pcre-JIT" class="std" class="tbody" >952ms (14751878)</td><td class="pcre-DFA" class="std" class="tbody" >4537ms (14751878)</td><td class="pcre" class="std" class="tbody" >2994ms (14751878)</td><td class="onig" class="std" class="tbody" >10865ms (14751878)</td><td class="regexp4Golang" class="raptor" class="tbody" >1811ms (14750958)</td><td class="regexp4" class="raptor" class="tbody" >819ms (14750958)</td><td class="regexp3" class="raptor" class="tbody" >1888ms (14750958)</td></tr>
     <tr><td class="pattern" ><table><tr class="raptor" ><td>&#34;[:w_]&#34;</tr></td><tr class="std" ><td>&#34;\w&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >4762ms (14751878)</td><td class="re2Golang" class="std" class="tbody" >29682ms (14751878)</td><td class="re2" class="std" class="tbody" >7066ms (14751878)</td><td class="pcre-JIT" class="std" class="tbody" >952ms (14751878)</td><td class="pcre-DFA" class="std" class="tbody" >4486ms (14751878)</td><td class="pcre" class="std" class="tbody" >2989ms (14751878)</td><td class="onig" class="std" class="tbody" >10663ms (14751878)</td><td class="regexp4Golang" class="raptor" class="tbody" >2472ms (14751878)</td><td class="regexp4" class="raptor" class="tbody" >1160ms (14751878)</td><td class="regexp3" class="raptor" class="tbody" >3171ms (14751878)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-zA-Z0-9_]&#34;</tr></td><tr class="raptor" ><td>&#34;[a-zA-Z0-9_]&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >4650ms (14751878)</td><td class="re2Golang" class="std" class="tbody" >29437ms (14751878)</td><td class="re2" class="std" class="tbody" >7121ms (14751878)</td><td class="pcre-JIT" class="std" class="tbody" >994ms (14751878)</td><td class="pcre-DFA" class="std" class="tbody" >4538ms (14751878)</td><td class="pcre" class="std" class="tbody" >3074ms (14751878)</td><td class="onig" class="std" class="tbody" >10483ms (14751878)</td><td class="regexp4Golang" class="raptor" class="tbody" >2735ms (14751878)</td><td class="regexp4" class="raptor" class="tbody" >1104ms (14751878)</td><td class="regexp3" class="raptor" class="tbody" >5260ms (14751878)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-zA-Z]+&#34;</tr></td><tr class="raptor" ><td>&#34;[a-zA-Z]+&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >2317ms (3495761)</td><td class="re2Golang" class="std" class="tbody" >7582ms (3495761)</td><td class="re2" class="std" class="tbody" >2048ms (3495761)</td><td class="pcre-JIT" class="std" class="tbody" >327ms (3495761)</td><td class="pcre-DFA" class="std" class="tbody" >1551ms (3495761)</td><td class="pcre" class="std" class="tbody" >1007ms (3495761)</td><td class="onig" class="std" class="tbody" >2956ms (3495761)</td><td class="regexp4Golang" class="raptor" class="tbody" >2250ms (3495761)</td><td class="regexp4" class="raptor" class="tbody" >860ms (3495761)</td><td class="regexp3" class="raptor" class="tbody" >2771ms (3495761)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[.\s]+&#34;</tr></td><tr class="raptor" ><td>&#34;[.:s]+&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >2205ms (991813)</td><td class="re2Golang" class="std" class="tbody" >9541ms (3430783)</td><td class="re2" class="std" class="tbody" >2036ms (3430783)</td><td class="pcre-JIT" class="std" class="tbody" >399ms (3430783)</td><td class="pcre-DFA" class="std" class="tbody" >1037ms (3430783)</td><td class="pcre" class="std" class="tbody" >949ms (3430783)</td><td class="onig" class="std" class="tbody" >2676ms (3430783)</td><td class="regexp4Golang" class="raptor" class="tbody" >2851ms (3430783)</td><td class="regexp4" class="raptor" class="tbody" >1363ms (3430783)</td><td class="regexp3" class="raptor" class="tbody" >3741ms (3430783)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;([^\n]+)&#34;</tr></td><tr class="raptor" ><td>&#34;&lt;[^\\n]+&gt;&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1591ms (314387)</td><td class="re2Golang" class="std" class="tbody" >5611ms (314387)</td><td class="re2" class="std" class="tbody" >430ms (314387)</td><td class="pcre-JIT" class="std" class="tbody" >82ms (314387)</td><td class="pcre-DFA" class="std" class="tbody" >1038ms (314387)</td><td class="pcre" class="std" class="tbody" >210ms (314387)</td><td class="onig" class="std" class="tbody" >697ms (314387)</td><td class="regexp4Golang" class="raptor" class="tbody" >1301ms (314387)</td><td class="regexp4" class="raptor" class="tbody" >578ms (314387)</td><td class="regexp3" class="raptor" class="tbody" >788ms (314387)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;e&#34;</tr></td><tr class="raptor" ><td>&#34;e&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >520ms (1781425)</td><td class="re2Golang" class="std" class="tbody" >2842ms (1781425)</td><td class="re2" class="std" class="tbody" >1000ms (1781425)</td><td class="pcre-JIT" class="std" class="tbody" >139ms (1781425)</td><td class="pcre-DFA" class="std" class="tbody" >439ms (1781425)</td><td class="pcre" class="std" class="tbody" >380ms (1781425)</td><td class="onig" class="std" class="tbody" >1434ms (1781425)</td><td class="regexp4Golang" class="raptor" class="tbody" >1739ms (1781425)</td><td class="regexp4" class="raptor" class="tbody" >663ms (1781425)</td><td class="regexp3" class="raptor" class="tbody" >1809ms (1781425)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(((((e)))))&#34;</tr></td><tr class="raptor" ><td>&#34;&lt;&lt;&lt;&lt;&lt;e&gt;&gt;&gt;&gt;&gt;&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >529ms (1781425)</td><td class="re2Golang" class="std" class="tbody" >4399ms (1781425)</td><td class="re2" class="std" class="tbody" >1001ms (1781425)</td><td class="pcre-JIT" class="std" class="tbody" >203ms (1781425)</td><td class="pcre-DFA" class="std" class="tbody" >1269ms (1781425)</td><td class="pcre" class="std" class="tbody" >1256ms (1781425)</td><td class="onig" class="std" class="tbody" >1971ms (1781425)</td><td class="regexp4Golang" class="raptor" class="tbody" >6168ms (1781425)</td><td class="regexp4" class="raptor" class="tbody" >2360ms (1781425)</td><td class="regexp3" class="raptor" class="tbody" >19939ms (1781425)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;((((((((((e))))))))))&#34;</tr></td><tr class="raptor" ><td>&#34;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;e&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >525ms (1781425)</td><td class="re2Golang" class="std" class="tbody" >6709ms (1781425)</td><td class="re2" class="std" class="tbody" >1006ms (1781425)</td><td class="pcre-JIT" class="std" class="tbody" >298ms (1781425)</td><td class="pcre-DFA" class="std" class="tbody" >1850ms (1781425)</td><td class="pcre" class="std" class="tbody" >1945ms (1781425)</td><td class="onig" class="std" class="tbody" >2176ms (1781425)</td><td class="regexp4Golang" class="raptor" class="tbody" >12171ms (1781425)</td><td class="regexp4" class="raptor" class="tbody" >4034ms (1781425)</td><td class="regexp3" class="raptor" class="tbody" >58376ms (1781425)</td></tr>
     <tr><td class="pattern" ><table><tr class="raptor" ><td>&#34;Twain&#34;</tr></td><tr class="std" ><td>&#34;Twain&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1022ms (2388)</td><td class="re2Golang" class="std" class="tbody" >12ms (2388)</td><td class="re2" class="std" class="tbody" >8ms (2388)</td><td class="pcre-JIT" class="std" class="tbody" >49ms (2388)</td><td class="pcre-DFA" class="std" class="tbody" >47ms (2388)</td><td class="pcre" class="std" class="tbody" >10ms (2388)</td><td class="onig" class="std" class="tbody" >52ms (2388)</td><td class="regexp4Golang" class="raptor" class="tbody" >1610ms (2388)</td><td class="regexp4" class="raptor" class="tbody" >589ms (2388)</td><td class="regexp3" class="raptor" class="tbody" >2450ms (2388)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(Twain)&#34;</tr></td><tr class="raptor" ><td>&#34;&lt;Twain&gt;&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1015ms (2388)</td><td class="re2Golang" class="std" class="tbody" >13ms (2388)</td><td class="re2" class="std" class="tbody" >8ms (2388)</td><td class="pcre-JIT" class="std" class="tbody" >49ms (2388)</td><td class="pcre-DFA" class="std" class="tbody" >48ms (2388)</td><td class="pcre" class="std" class="tbody" >14ms (2388)</td><td class="onig" class="std" class="tbody" >53ms (2388)</td><td class="regexp4Golang" class="raptor" class="tbody" >2294ms (2388)</td><td class="regexp4" class="raptor" class="tbody" >927ms (2388)</td><td class="regexp3" class="raptor" class="tbody" >6027ms (2388)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(?i)Twain&#34;</tr></td><tr class="raptor" ><td>&#34;#*Twain&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1337ms (2657)</td><td class="re2Golang" class="std" class="tbody" >3515ms (2657)</td><td class="re2" class="std" class="tbody" >166ms (2657)</td><td class="pcre-JIT" class="std" class="tbody" >51ms (2657)</td><td class="pcre-DFA" class="std" class="tbody" >287ms (2657)</td><td class="pcre" class="std" class="tbody" >203ms (2657)</td><td class="onig" class="std" class="tbody" >349ms (2657)</td><td class="regexp4Golang" class="raptor" class="tbody" >1616ms (2657)</td><td class="regexp4" class="raptor" class="tbody" >727ms (2657)</td><td class="regexp3" class="raptor" class="tbody" >2575ms (2657)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(?i:Tw)(?:(?:a?A?[i_I]{0,2})?[nN])&#34;</tr></td><tr class="raptor" ><td>&#34;(Tw)#*((a?A?[i_I]{0,2})?[nN])&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1375ms (2989)</td><td class="re2Golang" class="std" class="tbody" >3474ms (2989)</td><td class="re2" class="std" class="tbody" >168ms (2989)</td><td class="pcre-JIT" class="std" class="tbody" >56ms (2989)</td><td class="pcre-DFA" class="std" class="tbody" >319ms (2989)</td><td class="pcre" class="std" class="tbody" >236ms (2989)</td><td class="onig" class="std" class="tbody" >353ms (2989)</td><td class="regexp4Golang" class="raptor" class="tbody" >2154ms (2989)</td><td class="regexp4" class="raptor" class="tbody" >1021ms (2989)</td><td class="regexp3" class="raptor" class="tbody" >9216ms (2989)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-z]shing&#34;</tr></td><tr class="raptor" ><td>&#34;[a-z]shing&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1597ms (1877)</td><td class="re2Golang" class="std" class="tbody" >3614ms (1877)</td><td class="re2" class="std" class="tbody" >277ms (1877)</td><td class="pcre-JIT" class="std" class="tbody" >47ms (1877)</td><td class="pcre-DFA" class="std" class="tbody" >2302ms (1877)</td><td class="pcre" class="std" class="tbody" >1487ms (1877)</td><td class="onig" class="std" class="tbody" >49ms (1877)</td><td class="regexp4Golang" class="raptor" class="tbody" >3250ms (1877)</td><td class="regexp4" class="raptor" class="tbody" >1267ms (1877)</td><td class="regexp3" class="raptor" class="tbody" >5413ms (1877)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;Huck[a-zA-Z]+|Saw[a-zA-Z]+&#34;</tr></td><tr class="raptor" ><td>&#34;Huck[a-zA-Z]+|Saw[a-zA-Z]+&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1779ms (396)</td><td class="re2Golang" class="std" class="tbody" >4431ms (396)</td><td class="re2" class="std" class="tbody" >126ms (396)</td><td class="pcre-JIT" class="std" class="tbody" >8ms (396)</td><td class="pcre-DFA" class="std" class="tbody" >72ms (396)</td><td class="pcre" class="std" class="tbody" >70ms (396)</td><td class="onig" class="std" class="tbody" >117ms (396)</td><td class="regexp4Golang" class="raptor" class="tbody" >3894ms (396)</td><td class="regexp4" class="raptor" class="tbody" >1456ms (396)</td><td class="regexp3" class="raptor" class="tbody" >6599ms (396)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-q][^u-z]{13}x&#34;</tr></td><tr class="raptor" ><td>&#34;[a-q][^u-z]{13}x&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >4446ms (5021)</td><td class="re2Golang" class="std" class="tbody" >11181ms (5021)</td><td class="re2" class="std" class="tbody" >613ms (5021)</td><td class="pcre-JIT" class="std" class="tbody" >5ms (5021)</td><td class="pcre-DFA" class="std" class="tbody" >6169ms (5021)</td><td class="pcre" class="std" class="tbody" >1742ms (5021)</td><td class="onig" class="std" class="tbody" >135ms (5021)</td><td class="regexp4Golang" class="raptor" class="tbody" >9796ms (5021)</td><td class="regexp4" class="raptor" class="tbody" >3347ms (5021)</td><td class="regexp3" class="raptor" class="tbody" >10391ms (5021)</td></tr>
     <tr><td class="pattern" ><table><tr class="raptor" ><td>&#34;Tom|Sawyer|Huckleberry|Finn&#34;</tr></td><tr class="std" ><td>&#34;Tom|Sawyer|Huckleberry|Finn&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >3151ms (3015)</td><td class="re2Golang" class="std" class="tbody" >9003ms (3015)</td><td class="re2" class="std" class="tbody" >134ms (3015)</td><td class="pcre-JIT" class="std" class="tbody" >89ms (3015)</td><td class="pcre-DFA" class="std" class="tbody" >96ms (3015)</td><td class="pcre" class="std" class="tbody" >97ms (3015)</td><td class="onig" class="std" class="tbody" >141ms (3015)</td><td class="regexp4Golang" class="raptor" class="tbody" >6608ms (3015)</td><td class="regexp4" class="raptor" class="tbody" >2608ms (3015)</td><td class="regexp3" class="raptor" class="tbody" >10659ms (3015)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(Tom|Sawyer|Huckleberry|Finn)&#34;</tr></td><tr class="raptor" ><td>&#34;&lt;Tom|Sawyer|Huckleberry|Finn&gt;&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >3302ms (3015)</td><td class="re2Golang" class="std" class="tbody" >8876ms (3015)</td><td class="re2" class="std" class="tbody" >131ms (3015)</td><td class="pcre-JIT" class="std" class="tbody" >87ms (3015)</td><td class="pcre-DFA" class="std" class="tbody" >100ms (3015)</td><td class="pcre" class="std" class="tbody" >102ms (3015)</td><td class="onig" class="std" class="tbody" >142ms (3015)</td><td class="regexp4Golang" class="raptor" class="tbody" >7240ms (3015)</td><td class="regexp4" class="raptor" class="tbody" >2964ms (3015)</td><td class="regexp3" class="raptor" class="tbody" >23149ms (3015)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[hHeELlOo][hHeELlOo][hHeELlOo][hHeELlOo][hHeELlOo]&#34;</tr></td><tr class="raptor" ><td>&#34;[hHeELlOo][hHeELlOo][hHeELlOo][hHeELlOo][hHeELlOo]&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >3656ms (534)</td><td class="re2Golang" class="std" class="tbody" >4503ms (534)</td><td class="re2" class="std" class="tbody" >250ms (534)</td><td class="pcre-JIT" class="std" class="tbody" >247ms (534)</td><td class="pcre-DFA" class="std" class="tbody" >889ms (534)</td><td class="pcre" class="std" class="tbody" >638ms (534)</td><td class="onig" class="std" class="tbody" >687ms (534)</td><td class="regexp4Golang" class="raptor" class="tbody" >2903ms (534)</td><td class="regexp4" class="raptor" class="tbody" >1589ms (534)</td><td class="regexp3" class="raptor" class="tbody" >10916ms (534)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;Tom.{10,25}river|river.{10,25}Tom&#34;</tr></td><tr class="raptor" ><td></tr></td></table></td><td class="tre" class="std" class="tbody" >1844ms (2)</td><td class="re2Golang" class="std" class="tbody" >4541ms (2)</td><td class="re2" class="std" class="tbody" >152ms (2)</td><td class="pcre-JIT" class="std" class="tbody" >44ms (2)</td><td class="pcre-DFA" class="std" class="tbody" >247ms (2)</td><td class="pcre" class="std" class="tbody" >211ms (2)</td><td class="onig" class="std" class="tbody" >236ms (2)</td><td class="regexp4Golang" class="raptor" class="tbody" ><b>N/A</b></td><td class="regexp4" class="raptor" class="tbody" ><b>N/A</b></td><td class="regexp3" class="raptor" class="tbody" ><b>N/A</b></td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;ing[^a-zA-Z]&#34;</tr></td><tr class="raptor" ><td>&#34;ing[^a-zA-Z]&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1149ms (85956)</td><td class="re2Golang" class="std" class="tbody" >228ms (85956)</td><td class="re2" class="std" class="tbody" >111ms (85956)</td><td class="pcre-JIT" class="std" class="tbody" >54ms (85956)</td><td class="pcre-DFA" class="std" class="tbody" >243ms (85956)</td><td class="pcre" class="std" class="tbody" >140ms (85956)</td><td class="onig" class="std" class="tbody" >140ms (85956)</td><td class="regexp4Golang" class="raptor" class="tbody" >1611ms (85956)</td><td class="regexp4" class="raptor" class="tbody" >627ms (85956)</td><td class="regexp3" class="raptor" class="tbody" >3131ms (85956)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-zA-Z]ing[^a-zA-Z]&#34;</tr></td><tr class="raptor" ><td>&#34;[a-zA-Z]ing[^a-zA-Z]&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1859ms (85823)</td><td class="re2Golang" class="std" class="tbody" >3884ms (85823)</td><td class="re2" class="std" class="tbody" >309ms (85823)</td><td class="pcre-JIT" class="std" class="tbody" >56ms (85823)</td><td class="pcre-DFA" class="std" class="tbody" >2376ms (85823)</td><td class="pcre" class="std" class="tbody" >1549ms (85823)</td><td class="onig" class="std" class="tbody" >143ms (85823)</td><td class="regexp4Golang" class="raptor" class="tbody" >3274ms (85823)</td><td class="regexp4" class="raptor" class="tbody" >1328ms (85823)</td><td class="regexp3" class="raptor" class="tbody" >6761ms (85823)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;([a-zA-Z]+ing)&#34;</tr></td><tr class="raptor" ><td></tr></td></table></td><td class="tre" class="std" class="tbody" >2070ms (95863)</td><td class="re2Golang" class="std" class="tbody" >5411ms (95863)</td><td class="re2" class="std" class="tbody" >318ms (95863)</td><td class="pcre-JIT" class="std" class="tbody" >213ms (95863)</td><td class="pcre-DFA" class="std" class="tbody" >6616ms (95863)</td><td class="pcre" class="std" class="tbody" >4174ms (95863)</td><td class="onig" class="std" class="tbody" >2603ms (95863)</td><td class="regexp4Golang" class="raptor" class="tbody" ><b>N/A</b></td><td class="regexp4" class="raptor" class="tbody" ><b>N/A</b></td><td class="regexp3" class="raptor" class="tbody" ><b>N/A</b></td></tr>
     </tbody>
     </table>
   #+END_HTML

** Compile
*** Deps

    - *bash*
    - *make*
    - *gcc*
    - *g++*
    - *go*

*** get data

    1. =$ wget http://www.gutenberg.org/files/3200/old/mtent12.zip=
    2. =$ dos2unix mtent12.txt data.txt=
    3. =$ dos2unix data.txt=
    4. =$ rm mtent12*=

*** build benchmarks

    1. =$ ./rebuild.sh=
    2. =$ ./rebench.sh=

*** clean

    =$ ./reclean.sh=
