#+TITLE: Performance comparison of regular expression engines

the original test environment by *dark100* at
[[http://sljit.sourceforge.net/regex_perf.html][http://sljit.sourceforge.net/regex_perf.html]]

best view [here](https://nasciiboy.github.io/raptorVSworld/)

* Introduction

  Processing text or raw byte-sequence are among the common tasks performed by
  most software tools.  These tasks usually involve pattern matching
  algorithms, and the most popular tool for such purpose is regular
  expressions. Regular expressions has been evolved a lot since Kleene defined
  the regular sets in the 1950's. Today we have several widely used regular
  expression engines which have different [[http://en.wikipedia.org/wiki/Comparison_of_regular_expression_engines][features]] which makes any performance
  comparison a difficult task, since a *faster* engine is not necessary
  *better*. Depending on the use case it might be enough to know whether a
  POSIX compatible regular expression matches to a line, even the position of
  the match is unneeded (/grep utility/). On the contrary other use cases
  require the position of capturing brackets, unicode support, conditional and
  atomic block (handling a byte sequence as a single character, like 'sch' in
  German language) support just to name a few. The former case needs a less
  sophisticated algorithm, which is likely be much faster than the latter, but
  again, that does not mean the former is *better*. More about these engine
  types can be found [[http://sljit.sourceforge.net/regex_compare.html][here]].

* Participants

  The following popular engines were choosen:

  - [[http://www.pcre.org/][PCRE2 10.22]]
  - [[https://github.com/laurikari/tre/][tre 0.8.0]]
  - [[http://www.geocities.jp/kosako3/oniguruma/][Oniguruma 6.1.3]]
  - [[https://github.com/google/re2][re2 by Google]]
  - re2 (by Gogle) (Golang)
  - [[http://sljit.sourceforge.net/pcre.html][PCRE2 10.22 with sljit JIT compiler support]]


  and

  - [[https://github.com/nasciiboy/RecursiveRegexpRaptor][regexp3]]
  - [[https://github.com/nasciiboy/RecursiveRegexpRaptor-4][regexp4]]
  - [[https://github.com/nasciiboy/regexp4][regexp4 (Golang)]]


  Before anyone jump to any conclusions, I should note the followings:

  - The engines were not fine tuned (because of my lack of knowledge about
    their internal workings).  I just compiled them with the default options. I
    know enabling or disabling some features can heavily affect the results. If
    you feel that you have a better configuration just drop me an e-mail and I
    will update the results ([[mailto:nasciiboy@gmail.com]]).

  - The regular expression engines are compiled with =-O3= to allow the best performance.

  - This comparison page was inspired by the work of John Maddock (See his own
    regex comparison [[http://www.boost.org/doc/libs/1_41_0/libs/regex/doc/gcc-performance.html][here]]).  The input is also the same he used before:
    [[http://www.gutenberg.org/files/3200/old/mtent12.zip][mtent12.zip]].  It is a text file (e-book) which size is about 20 Mbytes.

  - Only common patterns are selected, they are not pathological cases nor have
    any PERL specific features. The comparison was caseful.

* Results
** x86-64 bit Intel Cerelon 847 1.1GHz (GCC 6.4.1, Go 1.9rc2 – GNU/Linux)

   #+BEGIN_HTML
     <table class="results" border="1" width="100%">
     <thead>
     <tr><th>Regular expression</th><th class="std" class="std" >tre</th><th class="std" class="std" >re2Golang</th><th class="std" class="std" >re2</th><th class="std" class="std" >pcre-JIT</th><th class="std" class="std" >pcre-DFA</th><th class="std" class="std" >pcre</th><th class="std" class="std" >onig</th><th class="raptor" class="raptor" >regexp4Golang</th><th class="raptor" class="raptor" >regexp4</th><th class="raptor" class="raptor" >regexp3</th></tr>
     </thead>
     <tbody>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;.|\n&#34;</tr></td><tr class="raptor" ><td>.</tr></td></table></td><td class="tre" class="std" class="tbody" >6353ms (19285324)</td><td class="re2Golang" class="std" class="tbody" >37946ms (19285324)</td><td class="re2" class="std" class="tbody" >10184ms (19285324)</td><td class="pcre-JIT" class="std" class="tbody" >1051ms (19285324)</td><td class="pcre-DFA" class="std" class="tbody" >5120ms (19285324)</td><td class="pcre" class="std" class="tbody" >4279ms (19285324)</td><td class="onig" class="std" class="tbody" >13731ms (19285324)</td><td class="regexp4Golang" class="raptor" class="tbody" >2340ms (19285324)</td><td class="regexp4" class="raptor" class="tbody" >641ms (19285324)</td><td class="regexp3" class="raptor" class="tbody" >1535ms (19285324)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;\d&#34;</tr></td><tr class="raptor" ><td>:d</tr></td></table></td><td class="tre" class="std" class="tbody" >989ms (27084)</td><td class="re2Golang" class="std" class="tbody" >3140ms (27084)</td><td class="re2" class="std" class="tbody" >145ms (27084)</td><td class="pcre-JIT" class="std" class="tbody" >55ms (27084)</td><td class="pcre-DFA" class="std" class="tbody" >64ms (27084)</td><td class="pcre" class="std" class="tbody" >63ms (27084)</td><td class="onig" class="std" class="tbody" >145ms (27084)</td><td class="regexp4Golang" class="raptor" class="tbody" >2064ms (27084)</td><td class="regexp4" class="raptor" class="tbody" >536ms (27084)</td><td class="regexp3" class="raptor" class="tbody" >1370ms (27084)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;\S&#34;</tr></td><tr class="raptor" ><td>:S</tr></td></table></td><td class="tre" class="std" class="tbody" >4583ms (15451664)</td><td class="re2Golang" class="std" class="tbody" >36049ms (15451664)</td><td class="re2" class="std" class="tbody" >8258ms (15451664)</td><td class="pcre-JIT" class="std" class="tbody" >903ms (15451664)</td><td class="pcre-DFA" class="std" class="tbody" >3152ms (15451664)</td><td class="pcre" class="std" class="tbody" >2913ms (15451664)</td><td class="onig" class="std" class="tbody" >10231ms (15451664)</td><td class="regexp4Golang" class="raptor" class="tbody" >2816ms (15451664)</td><td class="regexp4" class="raptor" class="tbody" >800ms (15451664)</td><td class="regexp3" class="raptor" class="tbody" >1462ms (15451664)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;\S+&#34;</tr></td><tr class="raptor" ><td>:S+</tr></td></table></td><td class="tre" class="std" class="tbody" >2444ms (3414592)</td><td class="re2Golang" class="std" class="tbody" >7573ms (3414592)</td><td class="re2" class="std" class="tbody" >2131ms (3414592)</td><td class="pcre-JIT" class="std" class="tbody" >309ms (3414592)</td><td class="pcre-DFA" class="std" class="tbody" >1565ms (3414592)</td><td class="pcre" class="std" class="tbody" >871ms (3414592)</td><td class="onig" class="std" class="tbody" >2914ms (3414592)</td><td class="regexp4Golang" class="raptor" class="tbody" >1821ms (3414592)</td><td class="regexp4" class="raptor" class="tbody" >634ms (3414592)</td><td class="regexp3" class="raptor" class="tbody" >1002ms (3414592)</td></tr>
     <tr><td class="pattern" ><table><tr class="raptor" ><td>:w</tr></td><tr class="std" ><td>&#34;\w&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >4640ms (14751878)</td><td class="re2Golang" class="std" class="tbody" >32723ms (14751878)</td><td class="re2" class="std" class="tbody" >7876ms (14751878)</td><td class="pcre-JIT" class="std" class="tbody" >966ms (14751878)</td><td class="pcre-DFA" class="std" class="tbody" >3038ms (14751878)</td><td class="pcre" class="std" class="tbody" >2934ms (14751878)</td><td class="onig" class="std" class="tbody" >10533ms (14751878)</td><td class="regexp4Golang" class="raptor" class="tbody" >2625ms (14750958)</td><td class="regexp4" class="raptor" class="tbody" >825ms (14750958)</td><td class="regexp3" class="raptor" class="tbody" >1455ms (14750958)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;\w&#34;</tr></td><tr class="raptor" ><td>[:w_]</tr></td></table></td><td class="tre" class="std" class="tbody" >4624ms (14751878)</td><td class="re2Golang" class="std" class="tbody" >32509ms (14751878)</td><td class="re2" class="std" class="tbody" >7823ms (14751878)</td><td class="pcre-JIT" class="std" class="tbody" >953ms (14751878)</td><td class="pcre-DFA" class="std" class="tbody" >3041ms (14751878)</td><td class="pcre" class="std" class="tbody" >2811ms (14751878)</td><td class="onig" class="std" class="tbody" >10527ms (14751878)</td><td class="regexp4Golang" class="raptor" class="tbody" >3251ms (14751878)</td><td class="regexp4" class="raptor" class="tbody" >1176ms (14751878)</td><td class="regexp3" class="raptor" class="tbody" >3081ms (14751878)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-zA-Z0-9_]&#34;</tr></td><tr class="raptor" ><td>[a-zA-Z0-9_]</tr></td></table></td><td class="tre" class="std" class="tbody" >4677ms (14751878)</td><td class="re2Golang" class="std" class="tbody" >30375ms (14751878)</td><td class="re2" class="std" class="tbody" >7874ms (14751878)</td><td class="pcre-JIT" class="std" class="tbody" >984ms (14751878)</td><td class="pcre-DFA" class="std" class="tbody" >3231ms (14751878)</td><td class="pcre" class="std" class="tbody" >3043ms (14751878)</td><td class="onig" class="std" class="tbody" >10356ms (14751878)</td><td class="regexp4Golang" class="raptor" class="tbody" >3513ms (14751878)</td><td class="regexp4" class="raptor" class="tbody" >1058ms (14751878)</td><td class="regexp3" class="raptor" class="tbody" >5416ms (14751878)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-zA-Z]+&#34;</tr></td><tr class="raptor" ><td>[a-zA-Z]+</tr></td></table></td><td class="tre" class="std" class="tbody" >2264ms (3495761)</td><td class="re2Golang" class="std" class="tbody" >10051ms (3495761)</td><td class="re2" class="std" class="tbody" >2206ms (3495761)</td><td class="pcre-JIT" class="std" class="tbody" >334ms (3495761)</td><td class="pcre-DFA" class="std" class="tbody" >1507ms (3495761)</td><td class="pcre" class="std" class="tbody" >963ms (3495761)</td><td class="onig" class="std" class="tbody" >3045ms (3495761)</td><td class="regexp4Golang" class="raptor" class="tbody" >2565ms (3495761)</td><td class="regexp4" class="raptor" class="tbody" >810ms (3495761)</td><td class="regexp3" class="raptor" class="tbody" >2585ms (3495761)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[.\s]+&#34;</tr></td><tr class="raptor" ><td>[.:s]+</tr></td></table></td><td class="tre" class="std" class="tbody" >1804ms (991813)</td><td class="re2Golang" class="std" class="tbody" >9508ms (3430783)</td><td class="re2" class="std" class="tbody" >2190ms (3430783)</td><td class="pcre-JIT" class="std" class="tbody" >372ms (3430783)</td><td class="pcre-DFA" class="std" class="tbody" >988ms (3430783)</td><td class="pcre" class="std" class="tbody" >913ms (3430783)</td><td class="onig" class="std" class="tbody" >2804ms (3430783)</td><td class="regexp4Golang" class="raptor" class="tbody" >3559ms (3430783)</td><td class="regexp4" class="raptor" class="tbody" >1297ms (3430783)</td><td class="regexp3" class="raptor" class="tbody" >3562ms (3430783)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;([^\n]+)&#34;</tr></td><tr class="raptor" ><td>&lt;[^\n]+&gt;</tr></td></table></td><td class="tre" class="std" class="tbody" >1509ms (314387)</td><td class="re2Golang" class="std" class="tbody" >5721ms (314387)</td><td class="re2" class="std" class="tbody" >464ms (314387)</td><td class="pcre-JIT" class="std" class="tbody" >81ms (314387)</td><td class="pcre-DFA" class="std" class="tbody" >1063ms (314387)</td><td class="pcre" class="std" class="tbody" >207ms (314387)</td><td class="onig" class="std" class="tbody" >696ms (314387)</td><td class="regexp4Golang" class="raptor" class="tbody" >1412ms (314387)</td><td class="regexp4" class="raptor" class="tbody" >541ms (314387)</td><td class="regexp3" class="raptor" class="tbody" >806ms (314387)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;e&#34;</tr></td><tr class="raptor" ><td>e</tr></td></table></td><td class="tre" class="std" class="tbody" >503ms (1781425)</td><td class="re2Golang" class="std" class="tbody" >3056ms (1781425)</td><td class="re2" class="std" class="tbody" >1014ms (1781425)</td><td class="pcre-JIT" class="std" class="tbody" >135ms (1781425)</td><td class="pcre-DFA" class="std" class="tbody" >442ms (1781425)</td><td class="pcre" class="std" class="tbody" >353ms (1781425)</td><td class="onig" class="std" class="tbody" >1465ms (1781425)</td><td class="regexp4Golang" class="raptor" class="tbody" >2495ms (1781425)</td><td class="regexp4" class="raptor" class="tbody" >644ms (1781425)</td><td class="regexp3" class="raptor" class="tbody" >1490ms (1781425)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(((((e)))))&#34;</tr></td><tr class="raptor" ><td>&lt;&lt;&lt;&lt;&lt;e&gt;&gt;&gt;&gt;&gt;</tr></td></table></td><td class="tre" class="std" class="tbody" >507ms (1781425)</td><td class="re2Golang" class="std" class="tbody" >4363ms (1781425)</td><td class="re2" class="std" class="tbody" >999ms (1781425)</td><td class="pcre-JIT" class="std" class="tbody" >205ms (1781425)</td><td class="pcre-DFA" class="std" class="tbody" >1123ms (1781425)</td><td class="pcre" class="std" class="tbody" >1305ms (1781425)</td><td class="onig" class="std" class="tbody" >1993ms (1781425)</td><td class="regexp4Golang" class="raptor" class="tbody" >11683ms (1781425)</td><td class="regexp4" class="raptor" class="tbody" >2149ms (1781425)</td><td class="regexp3" class="raptor" class="tbody" >17157ms (1781425)</td></tr>
     <tr><td class="pattern" ><table><tr class="raptor" ><td>&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;&lt;e&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;&gt;</tr></td><tr class="std" ><td>&#34;((((((((((e))))))))))&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >499ms (1781425)</td><td class="re2Golang" class="std" class="tbody" >6538ms (1781425)</td><td class="re2" class="std" class="tbody" >997ms (1781425)</td><td class="pcre-JIT" class="std" class="tbody" >296ms (1781425)</td><td class="pcre-DFA" class="std" class="tbody" >1719ms (1781425)</td><td class="pcre" class="std" class="tbody" >2022ms (1781425)</td><td class="onig" class="std" class="tbody" >2186ms (1781425)</td><td class="regexp4Golang" class="raptor" class="tbody" >21299ms (1781425)</td><td class="regexp4" class="raptor" class="tbody" >3661ms (1781425)</td><td class="regexp3" class="raptor" class="tbody" >48145ms (1781425)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;Twain&#34;</tr></td><tr class="raptor" ><td>Twain</tr></td></table></td><td class="tre" class="std" class="tbody" >954ms (2388)</td><td class="re2Golang" class="std" class="tbody" >12ms (2388)</td><td class="re2" class="std" class="tbody" >8ms (2388)</td><td class="pcre-JIT" class="std" class="tbody" >49ms (2388)</td><td class="pcre-DFA" class="std" class="tbody" >47ms (2388)</td><td class="pcre" class="std" class="tbody" >10ms (2388)</td><td class="onig" class="std" class="tbody" >52ms (2388)</td><td class="regexp4Golang" class="raptor" class="tbody" >2360ms (2388)</td><td class="regexp4" class="raptor" class="tbody" >554ms (2388)</td><td class="regexp3" class="raptor" class="tbody" >2567ms (2388)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(Twain)&#34;</tr></td><tr class="raptor" ><td>&lt;Twain&gt;</tr></td></table></td><td class="tre" class="std" class="tbody" >985ms (2388)</td><td class="re2Golang" class="std" class="tbody" >13ms (2388)</td><td class="re2" class="std" class="tbody" >8ms (2388)</td><td class="pcre-JIT" class="std" class="tbody" >49ms (2388)</td><td class="pcre-DFA" class="std" class="tbody" >48ms (2388)</td><td class="pcre" class="std" class="tbody" >14ms (2388)</td><td class="onig" class="std" class="tbody" >53ms (2388)</td><td class="regexp4Golang" class="raptor" class="tbody" >3705ms (2388)</td><td class="regexp4" class="raptor" class="tbody" >922ms (2388)</td><td class="regexp3" class="raptor" class="tbody" >5619ms (2388)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(?i)Twain&#34;</tr></td><tr class="raptor" ><td>#*Twain</tr></td></table></td><td class="tre" class="std" class="tbody" >1238ms (2657)</td><td class="re2Golang" class="std" class="tbody" >3489ms (2657)</td><td class="re2" class="std" class="tbody" >168ms (2657)</td><td class="pcre-JIT" class="std" class="tbody" >51ms (2657)</td><td class="pcre-DFA" class="std" class="tbody" >286ms (2657)</td><td class="pcre" class="std" class="tbody" >193ms (2657)</td><td class="onig" class="std" class="tbody" >340ms (2657)</td><td class="regexp4Golang" class="raptor" class="tbody" >2371ms (2657)</td><td class="regexp4" class="raptor" class="tbody" >715ms (2657)</td><td class="regexp3" class="raptor" class="tbody" >2689ms (2657)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;((T|t)([wW])(a|A)i?I?([nN]))&#34;</tr></td><tr class="raptor" ><td>&lt;&lt;T|t&gt;&lt;[wW]&gt;&lt;a|A&gt;i?I?&lt;[nN]&gt;&gt;</tr></td></table></td><td class="tre" class="std" class="tbody" >1669ms (2658)</td><td class="re2Golang" class="std" class="tbody" >5077ms (2658)</td><td class="re2" class="std" class="tbody" >169ms (2658)</td><td class="pcre-JIT" class="std" class="tbody" >74ms (2658)</td><td class="pcre-DFA" class="std" class="tbody" >458ms (2658)</td><td class="pcre" class="std" class="tbody" >576ms (2658)</td><td class="onig" class="std" class="tbody" >358ms (2658)</td><td class="regexp4Golang" class="raptor" class="tbody" >6980ms (2658)</td><td class="regexp4" class="raptor" class="tbody" >2278ms (2658)</td><td class="regexp3" class="raptor" class="tbody" >17356ms (2658)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(T+([w]?(a{1}(i+(n*))))){1}&#34;</tr></td><tr class="raptor" ><td>&lt;T+&lt;[w]?&lt;a{1}&lt;i+&lt;n*&gt;&gt;&gt;&gt;&gt;{1}</tr></td></table></td><td class="tre" class="std" class="tbody" >1126ms (2419)</td><td class="re2Golang" class="std" class="tbody" >51ms (2419)</td><td class="re2" class="std" class="tbody" >8ms (2419)</td><td class="pcre-JIT" class="std" class="tbody" >7ms (2419)</td><td class="pcre-DFA" class="std" class="tbody" >58ms (2419)</td><td class="pcre" class="std" class="tbody" >25ms (2419)</td><td class="onig" class="std" class="tbody" >155ms (2419)</td><td class="regexp4Golang" class="raptor" class="tbody" >3747ms (2419)</td><td class="regexp4" class="raptor" class="tbody" >929ms (2419)</td><td class="regexp3" class="raptor" class="tbody" >12427ms (2419)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(?:T+(?:[w]?(?:a{1}(?:i+(?:n*))))){1}&#34;</tr></td><tr class="raptor" ><td>(T+([w]?(a{1}(i+(n*))))){1}</tr></td></table></td><td class="tre" class="std" class="tbody" >1118ms (2419)</td><td class="re2Golang" class="std" class="tbody" >40ms (2419)</td><td class="re2" class="std" class="tbody" >8ms (2419)</td><td class="pcre-JIT" class="std" class="tbody" >6ms (2419)</td><td class="pcre-DFA" class="std" class="tbody" >58ms (2419)</td><td class="pcre" class="std" class="tbody" >20ms (2419)</td><td class="onig" class="std" class="tbody" >154ms (2419)</td><td class="regexp4Golang" class="raptor" class="tbody" >3580ms (2419)</td><td class="regexp4" class="raptor" class="tbody" >807ms (2419)</td><td class="regexp3" class="raptor" class="tbody" >11593ms (2419)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-z]shing&#34;</tr></td><tr class="raptor" ><td>[a-z]shing</tr></td></table></td><td class="tre" class="std" class="tbody" >1509ms (1877)</td><td class="re2Golang" class="std" class="tbody" >3672ms (1877)</td><td class="re2" class="std" class="tbody" >263ms (1877)</td><td class="pcre-JIT" class="std" class="tbody" >46ms (1877)</td><td class="pcre-DFA" class="std" class="tbody" >2319ms (1877)</td><td class="pcre" class="std" class="tbody" >1486ms (1877)</td><td class="onig" class="std" class="tbody" >49ms (1877)</td><td class="regexp4Golang" class="raptor" class="tbody" >3826ms (1877)</td><td class="regexp4" class="raptor" class="tbody" >1231ms (1877)</td><td class="regexp3" class="raptor" class="tbody" >5120ms (1877)</td></tr>
     <tr><td class="pattern" ><table><tr class="raptor" ><td>Huck[a-zA-Z]+|Saw[a-zA-Z]+</tr></td><tr class="std" ><td>&#34;Huck[a-zA-Z]+|Saw[a-zA-Z]+&#34;</tr></td></table></td><td class="tre" class="std" class="tbody" >1470ms (396)</td><td class="re2Golang" class="std" class="tbody" >4451ms (396)</td><td class="re2" class="std" class="tbody" >132ms (396)</td><td class="pcre-JIT" class="std" class="tbody" >8ms (396)</td><td class="pcre-DFA" class="std" class="tbody" >73ms (396)</td><td class="pcre" class="std" class="tbody" >70ms (396)</td><td class="onig" class="std" class="tbody" >135ms (396)</td><td class="regexp4Golang" class="raptor" class="tbody" >3884ms (396)</td><td class="regexp4" class="raptor" class="tbody" >1393ms (396)</td><td class="regexp3" class="raptor" class="tbody" >7524ms (396)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-q][^u-z]{13}x&#34;</tr></td><tr class="raptor" ><td>[a-q][^u-z]{13}x</tr></td></table></td><td class="tre" class="std" class="tbody" >4258ms (5021)</td><td class="re2Golang" class="std" class="tbody" >10974ms (5021)</td><td class="re2" class="std" class="tbody" >570ms (5021)</td><td class="pcre-JIT" class="std" class="tbody" >5ms (5021)</td><td class="pcre-DFA" class="std" class="tbody" >6344ms (5021)</td><td class="pcre" class="std" class="tbody" >1763ms (5021)</td><td class="onig" class="std" class="tbody" >152ms (5021)</td><td class="regexp4Golang" class="raptor" class="tbody" >10747ms (5021)</td><td class="regexp4" class="raptor" class="tbody" >3498ms (5021)</td><td class="regexp3" class="raptor" class="tbody" >9601ms (5021)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;Tom|Sawyer|Huckleberry|Finn&#34;</tr></td><tr class="raptor" ><td>Tom|Sawyer|Huckleberry|Finn</tr></td></table></td><td class="tre" class="std" class="tbody" >2637ms (3015)</td><td class="re2Golang" class="std" class="tbody" >8341ms (3015)</td><td class="re2" class="std" class="tbody" >135ms (3015)</td><td class="pcre-JIT" class="std" class="tbody" >81ms (3015)</td><td class="pcre-DFA" class="std" class="tbody" >99ms (3015)</td><td class="pcre" class="std" class="tbody" >94ms (3015)</td><td class="onig" class="std" class="tbody" >157ms (3015)</td><td class="regexp4Golang" class="raptor" class="tbody" >6870ms (3015)</td><td class="regexp4" class="raptor" class="tbody" >2495ms (3015)</td><td class="regexp3" class="raptor" class="tbody" >11013ms (3015)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;(Tom|Sawyer|Huckleberry|Finn)&#34;</tr></td><tr class="raptor" ><td>&lt;Tom|Sawyer|Huckleberry|Finn&gt;</tr></td></table></td><td class="tre" class="std" class="tbody" >2593ms (3015)</td><td class="re2Golang" class="std" class="tbody" >9028ms (3015)</td><td class="re2" class="std" class="tbody" >135ms (3015)</td><td class="pcre-JIT" class="std" class="tbody" >80ms (3015)</td><td class="pcre-DFA" class="std" class="tbody" >101ms (3015)</td><td class="pcre" class="std" class="tbody" >100ms (3015)</td><td class="onig" class="std" class="tbody" >158ms (3015)</td><td class="regexp4Golang" class="raptor" class="tbody" >8206ms (3015)</td><td class="regexp4" class="raptor" class="tbody" >2855ms (3015)</td><td class="regexp3" class="raptor" class="tbody" >19578ms (3015)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[hHeELlOo][hHeELlOo][hHeELlOo][hHeELlOo][hHeELlOo]&#34;</tr></td><tr class="raptor" ><td>[hHeELlOo][hHeELlOo][hHeELlOo][hHeELlOo][hHeELlOo]</tr></td></table></td><td class="tre" class="std" class="tbody" >2707ms (534)</td><td class="re2Golang" class="std" class="tbody" >4438ms (534)</td><td class="re2" class="std" class="tbody" >253ms (534)</td><td class="pcre-JIT" class="std" class="tbody" >238ms (534)</td><td class="pcre-DFA" class="std" class="tbody" >880ms (534)</td><td class="pcre" class="std" class="tbody" >624ms (534)</td><td class="onig" class="std" class="tbody" >687ms (534)</td><td class="regexp4Golang" class="raptor" class="tbody" >3618ms (534)</td><td class="regexp4" class="raptor" class="tbody" >1518ms (534)</td><td class="regexp3" class="raptor" class="tbody" >11236ms (534)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;Tom.{10,25}river|river.{10,25}Tom&#34;</tr></td><tr class="raptor" ><td>Tom(river|\n){10,25}#!river|river(Tom|\n){10,25}#!Tom</tr></td></table></td><td class="tre" class="std" class="tbody" >1684ms (2)</td><td class="re2Golang" class="std" class="tbody" >4523ms (2)</td><td class="re2" class="std" class="tbody" >242ms (2)</td><td class="pcre-JIT" class="std" class="tbody" >44ms (2)</td><td class="pcre-DFA" class="std" class="tbody" >247ms (2)</td><td class="pcre" class="std" class="tbody" >205ms (2)</td><td class="onig" class="std" class="tbody" >248ms (2)</td><td class="regexp4Golang" class="raptor" class="tbody" >3899ms (2)</td><td class="regexp4" class="raptor" class="tbody" >1422ms (2)</td><td class="regexp3" class="raptor" class="tbody" >12690ms (2)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;ing[^a-zA-Z]&#34;</tr></td><tr class="raptor" ><td>ing[^a-zA-Z]</tr></td></table></td><td class="tre" class="std" class="tbody" >1076ms (85956)</td><td class="re2Golang" class="std" class="tbody" >217ms (85956)</td><td class="re2" class="std" class="tbody" >112ms (85956)</td><td class="pcre-JIT" class="std" class="tbody" >53ms (85956)</td><td class="pcre-DFA" class="std" class="tbody" >249ms (85956)</td><td class="pcre" class="std" class="tbody" >136ms (85956)</td><td class="onig" class="std" class="tbody" >137ms (85956)</td><td class="regexp4Golang" class="raptor" class="tbody" >2368ms (85956)</td><td class="regexp4" class="raptor" class="tbody" >596ms (85956)</td><td class="regexp3" class="raptor" class="tbody" >3156ms (85956)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;[a-zA-Z]ing[^a-zA-Z]&#34;</tr></td><tr class="raptor" ><td>[a-zA-Z]ing[^a-zA-Z]</tr></td></table></td><td class="tre" class="std" class="tbody" >1775ms (85823)</td><td class="re2Golang" class="std" class="tbody" >3889ms (85823)</td><td class="re2" class="std" class="tbody" >301ms (85823)</td><td class="pcre-JIT" class="std" class="tbody" >56ms (85823)</td><td class="pcre-DFA" class="std" class="tbody" >2388ms (85823)</td><td class="pcre" class="std" class="tbody" >1526ms (85823)</td><td class="onig" class="std" class="tbody" >140ms (85823)</td><td class="regexp4Golang" class="raptor" class="tbody" >4026ms (85823)</td><td class="regexp4" class="raptor" class="tbody" >1276ms (85823)</td><td class="regexp3" class="raptor" class="tbody" >6593ms (85823)</td></tr>
     <tr><td class="pattern" ><table><tr class="std" ><td>&#34;([a-zA-Z]+ing)&#34;</tr></td><tr class="raptor" ><td>&lt;(ing|:A)+#!ing((ing|:A)*#!ing)*&gt;</tr></td></table></td><td class="tre" class="std" class="tbody" >2038ms (95863)</td><td class="re2Golang" class="std" class="tbody" >5392ms (95863)</td><td class="re2" class="std" class="tbody" >319ms (95863)</td><td class="pcre-JIT" class="std" class="tbody" >213ms (95863)</td><td class="pcre-DFA" class="std" class="tbody" >5420ms (95863)</td><td class="pcre" class="std" class="tbody" >4106ms (95863)</td><td class="onig" class="std" class="tbody" >2468ms (95863)</td><td class="regexp4Golang" class="raptor" class="tbody" >16710ms (95863)</td><td class="regexp4" class="raptor" class="tbody" >6403ms (95863)</td><td class="regexp3" class="raptor" class="tbody" >26462ms (95863)</td></tr>
     </tbody>
     </table>
   #+END_HTML

** Compile
*** Deps

    - *bash*
    - *make*
    - *gcc*
    - *g++*
    - *go*

*** get data


    1. =$ wget http://www.gutenberg.org/files/3200/old/mtent12.zip=
    2. =$ dos2unix mtent12.txt data.txt=
    3. =$ dos2unix data.txt=
    4. =$ rm mtent12*=


*** build benchmarks

    1. =$ ./rebuild.sh=
    2. =$ ./rebench.sh=

*** clean

    =$ ./reclean.sh=
